<?php
namespace HubloyMembership\Helper;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

/**
 * Currency helper
 *
 * @since 1.0.0
 */
class Currency {

	/**
	 * List currencies
	 *
	 * @since 1.0.0
	 *
	 * @return array
	 */
	public static function list_currencies() {
		static $currencies;
		if ( ! isset( $currencies ) ) {
			$currencies = array_unique(
				apply_filters(
					'hubloy-membership_currencies',
					array(
						'AED' => __( 'United Arab Emirates dirham', 'hubloy-membership' ),
						'AFN' => __( 'Afghan afghani', 'hubloy-membership' ),
						'ALL' => __( 'Albanian lek', 'hubloy-membership' ),
						'AMD' => __( 'Armenian dram', 'hubloy-membership' ),
						'ANG' => __( 'Netherlands Antillean guilder', 'hubloy-membership' ),
						'AOA' => __( 'Angolan kwanza', 'hubloy-membership' ),
						'ARS' => __( 'Argentine peso', 'hubloy-membership' ),
						'AUD' => __( 'Australian dollar', 'hubloy-membership' ),
						'AWG' => __( 'Aruban florin', 'hubloy-membership' ),
						'AZN' => __( 'Azerbaijani manat', 'hubloy-membership' ),
						'BAM' => __( 'Bosnia and Herzegovina convertible mark', 'hubloy-membership' ),
						'BBD' => __( 'Barbadian dollar', 'hubloy-membership' ),
						'BDT' => __( 'Bangladeshi taka', 'hubloy-membership' ),
						'BGN' => __( 'Bulgarian lev', 'hubloy-membership' ),
						'BHD' => __( 'Bahraini dinar', 'hubloy-membership' ),
						'BIF' => __( 'Burundian franc', 'hubloy-membership' ),
						'BMD' => __( 'Bermudian dollar', 'hubloy-membership' ),
						'BND' => __( 'Brunei dollar', 'hubloy-membership' ),
						'BOB' => __( 'Bolivian boliviano', 'hubloy-membership' ),
						'BRL' => __( 'Brazilian real', 'hubloy-membership' ),
						'BSD' => __( 'Bahamian dollar', 'hubloy-membership' ),
						'BTC' => __( 'Bitcoin', 'hubloy-membership' ),
						'BTN' => __( 'Bhutanese ngultrum', 'hubloy-membership' ),
						'BWP' => __( 'Botswana pula', 'hubloy-membership' ),
						'BYR' => __( 'Belarusian ruble (old)', 'hubloy-membership' ),
						'BYN' => __( 'Belarusian ruble', 'hubloy-membership' ),
						'BZD' => __( 'Belize dollar', 'hubloy-membership' ),
						'CAD' => __( 'Canadian dollar', 'hubloy-membership' ),
						'CDF' => __( 'Congolese franc', 'hubloy-membership' ),
						'CHF' => __( 'Swiss franc', 'hubloy-membership' ),
						'CLP' => __( 'Chilean peso', 'hubloy-membership' ),
						'CNY' => __( 'Chinese yuan', 'hubloy-membership' ),
						'COP' => __( 'Colombian peso', 'hubloy-membership' ),
						'CRC' => __( 'Costa Rican col&oacute;n', 'hubloy-membership' ),
						'CUC' => __( 'Cuban convertible peso', 'hubloy-membership' ),
						'CUP' => __( 'Cuban peso', 'hubloy-membership' ),
						'CVE' => __( 'Cape Verdean escudo', 'hubloy-membership' ),
						'CZK' => __( 'Czech koruna', 'hubloy-membership' ),
						'DJF' => __( 'Djiboutian franc', 'hubloy-membership' ),
						'DKK' => __( 'Danish krone', 'hubloy-membership' ),
						'DOP' => __( 'Dominican peso', 'hubloy-membership' ),
						'DZD' => __( 'Algerian dinar', 'hubloy-membership' ),
						'EGP' => __( 'Egyptian pound', 'hubloy-membership' ),
						'ERN' => __( 'Eritrean nakfa', 'hubloy-membership' ),
						'ETB' => __( 'Ethiopian birr', 'hubloy-membership' ),
						'EUR' => __( 'Euro', 'hubloy-membership' ),
						'FJD' => __( 'Fijian dollar', 'hubloy-membership' ),
						'FKP' => __( 'Falkland Islands pound', 'hubloy-membership' ),
						'GBP' => __( 'Pound sterling', 'hubloy-membership' ),
						'GEL' => __( 'Georgian lari', 'hubloy-membership' ),
						'GGP' => __( 'Guernsey pound', 'hubloy-membership' ),
						'GHS' => __( 'Ghana cedi', 'hubloy-membership' ),
						'GIP' => __( 'Gibraltar pound', 'hubloy-membership' ),
						'GMD' => __( 'Gambian dalasi', 'hubloy-membership' ),
						'GNF' => __( 'Guinean franc', 'hubloy-membership' ),
						'GTQ' => __( 'Guatemalan quetzal', 'hubloy-membership' ),
						'GYD' => __( 'Guyanese dollar', 'hubloy-membership' ),
						'HKD' => __( 'Hong Kong dollar', 'hubloy-membership' ),
						'HNL' => __( 'Honduran lempira', 'hubloy-membership' ),
						'HRK' => __( 'Croatian kuna', 'hubloy-membership' ),
						'HTG' => __( 'Haitian gourde', 'hubloy-membership' ),
						'HUF' => __( 'Hungarian forint', 'hubloy-membership' ),
						'IDR' => __( 'Indonesian rupiah', 'hubloy-membership' ),
						'ILS' => __( 'Israeli new shekel', 'hubloy-membership' ),
						'IMP' => __( 'Manx pound', 'hubloy-membership' ),
						'INR' => __( 'Indian rupee', 'hubloy-membership' ),
						'IQD' => __( 'Iraqi dinar', 'hubloy-membership' ),
						'IRR' => __( 'Iranian rial', 'hubloy-membership' ),
						'IRT' => __( 'Iranian toman', 'hubloy-membership' ),
						'ISK' => __( 'Icelandic kr&oacute;na', 'hubloy-membership' ),
						'JEP' => __( 'Jersey pound', 'hubloy-membership' ),
						'JMD' => __( 'Jamaican dollar', 'hubloy-membership' ),
						'JOD' => __( 'Jordanian dinar', 'hubloy-membership' ),
						'JPY' => __( 'Japanese yen', 'hubloy-membership' ),
						'KES' => __( 'Kenyan shilling', 'hubloy-membership' ),
						'KGS' => __( 'Kyrgyzstani som', 'hubloy-membership' ),
						'KHR' => __( 'Cambodian riel', 'hubloy-membership' ),
						'KMF' => __( 'Comorian franc', 'hubloy-membership' ),
						'KPW' => __( 'North Korean won', 'hubloy-membership' ),
						'KRW' => __( 'South Korean won', 'hubloy-membership' ),
						'KWD' => __( 'Kuwaiti dinar', 'hubloy-membership' ),
						'KYD' => __( 'Cayman Islands dollar', 'hubloy-membership' ),
						'KZT' => __( 'Kazakhstani tenge', 'hubloy-membership' ),
						'LAK' => __( 'Lao kip', 'hubloy-membership' ),
						'LBP' => __( 'Lebanese pound', 'hubloy-membership' ),
						'LKR' => __( 'Sri Lankan rupee', 'hubloy-membership' ),
						'LRD' => __( 'Liberian dollar', 'hubloy-membership' ),
						'LSL' => __( 'Lesotho loti', 'hubloy-membership' ),
						'LYD' => __( 'Libyan dinar', 'hubloy-membership' ),
						'MAD' => __( 'Moroccan dirham', 'hubloy-membership' ),
						'MDL' => __( 'Moldovan leu', 'hubloy-membership' ),
						'MGA' => __( 'Malagasy ariary', 'hubloy-membership' ),
						'MKD' => __( 'Macedonian denar', 'hubloy-membership' ),
						'MMK' => __( 'Burmese kyat', 'hubloy-membership' ),
						'MNT' => __( 'Mongolian t&ouml;gr&ouml;g', 'hubloy-membership' ),
						'MOP' => __( 'Macanese pataca', 'hubloy-membership' ),
						'MRU' => __( 'Mauritanian ouguiya', 'hubloy-membership' ),
						'MUR' => __( 'Mauritian rupee', 'hubloy-membership' ),
						'MVR' => __( 'Maldivian rufiyaa', 'hubloy-membership' ),
						'MWK' => __( 'Malawian kwacha', 'hubloy-membership' ),
						'MXN' => __( 'Mexican peso', 'hubloy-membership' ),
						'MYR' => __( 'Malaysian ringgit', 'hubloy-membership' ),
						'MZN' => __( 'Mozambican metical', 'hubloy-membership' ),
						'NAD' => __( 'Namibian dollar', 'hubloy-membership' ),
						'NGN' => __( 'Nigerian naira', 'hubloy-membership' ),
						'NIO' => __( 'Nicaraguan c&oacute;rdoba', 'hubloy-membership' ),
						'NOK' => __( 'Norwegian krone', 'hubloy-membership' ),
						'NPR' => __( 'Nepalese rupee', 'hubloy-membership' ),
						'NZD' => __( 'New Zealand dollar', 'hubloy-membership' ),
						'OMR' => __( 'Omani rial', 'hubloy-membership' ),
						'PAB' => __( 'Panamanian balboa', 'hubloy-membership' ),
						'PEN' => __( 'Sol', 'hubloy-membership' ),
						'PGK' => __( 'Papua New Guinean kina', 'hubloy-membership' ),
						'PHP' => __( 'Philippine peso', 'hubloy-membership' ),
						'PKR' => __( 'Pakistani rupee', 'hubloy-membership' ),
						'PLN' => __( 'Polish z&#x142;oty', 'hubloy-membership' ),
						'PRB' => __( 'Transnistrian ruble', 'hubloy-membership' ),
						'PYG' => __( 'Paraguayan guaran&iacute;', 'hubloy-membership' ),
						'QAR' => __( 'Qatari riyal', 'hubloy-membership' ),
						'RON' => __( 'Romanian leu', 'hubloy-membership' ),
						'RSD' => __( 'Serbian dinar', 'hubloy-membership' ),
						'RUB' => __( 'Russian ruble', 'hubloy-membership' ),
						'RWF' => __( 'Rwandan franc', 'hubloy-membership' ),
						'SAR' => __( 'Saudi riyal', 'hubloy-membership' ),
						'SBD' => __( 'Solomon Islands dollar', 'hubloy-membership' ),
						'SCR' => __( 'Seychellois rupee', 'hubloy-membership' ),
						'SDG' => __( 'Sudanese pound', 'hubloy-membership' ),
						'SEK' => __( 'Swedish krona', 'hubloy-membership' ),
						'SGD' => __( 'Singapore dollar', 'hubloy-membership' ),
						'SHP' => __( 'Saint Helena pound', 'hubloy-membership' ),
						'SLL' => __( 'Sierra Leonean leone', 'hubloy-membership' ),
						'SOS' => __( 'Somali shilling', 'hubloy-membership' ),
						'SRD' => __( 'Surinamese dollar', 'hubloy-membership' ),
						'SSP' => __( 'South Sudanese pound', 'hubloy-membership' ),
						'STN' => __( 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe dobra', 'hubloy-membership' ),
						'SYP' => __( 'Syrian pound', 'hubloy-membership' ),
						'SZL' => __( 'Swazi lilangeni', 'hubloy-membership' ),
						'THB' => __( 'Thai baht', 'hubloy-membership' ),
						'TJS' => __( 'Tajikistani somoni', 'hubloy-membership' ),
						'TMT' => __( 'Turkmenistan manat', 'hubloy-membership' ),
						'TND' => __( 'Tunisian dinar', 'hubloy-membership' ),
						'TOP' => __( 'Tongan pa&#x2bb;anga', 'hubloy-membership' ),
						'TRY' => __( 'Turkish lira', 'hubloy-membership' ),
						'TTD' => __( 'Trinidad and Tobago dollar', 'hubloy-membership' ),
						'TWD' => __( 'New Taiwan dollar', 'hubloy-membership' ),
						'TZS' => __( 'Tanzanian shilling', 'hubloy-membership' ),
						'UAH' => __( 'Ukrainian hryvnia', 'hubloy-membership' ),
						'UGX' => __( 'Ugandan shilling', 'hubloy-membership' ),
						'USD' => __( 'United States (US) dollar', 'hubloy-membership' ),
						'UYU' => __( 'Uruguayan peso', 'hubloy-membership' ),
						'UZS' => __( 'Uzbekistani som', 'hubloy-membership' ),
						'VEF' => __( 'Venezuelan bol&iacute;var', 'hubloy-membership' ),
						'VES' => __( 'Bol&iacute;var soberano', 'hubloy-membership' ),
						'VND' => __( 'Vietnamese &#x111;&#x1ed3;ng', 'hubloy-membership' ),
						'VUV' => __( 'Vanuatu vatu', 'hubloy-membership' ),
						'WST' => __( 'Samoan t&#x101;l&#x101;', 'hubloy-membership' ),
						'XAF' => __( 'Central African CFA franc', 'hubloy-membership' ),
						'XCD' => __( 'East Caribbean dollar', 'hubloy-membership' ),
						'XOF' => __( 'West African CFA franc', 'hubloy-membership' ),
						'XPF' => __( 'CFP franc', 'hubloy-membership' ),
						'YER' => __( 'Yemeni rial', 'hubloy-membership' ),
						'ZAR' => __( 'South African rand', 'hubloy-membership' ),
						'ZMW' => __( 'Zambian kwacha', 'hubloy-membership' ),
					)
				)
			);
		}

		return $currencies;
	}


	public static function get_currency_symbol( $currency = 'USD' ) {
		$symbols         = apply_filters(
			'hubloy-membership_currency_symbols',
			array(
				'AED' => '&#x62f;.&#x625;',
				'AFN' => '&#x60b;',
				'ALL' => 'L',
				'AMD' => 'AMD',
				'ANG' => '&fnof;',
				'AOA' => 'Kz',
				'ARS' => '&#36;',
				'AUD' => '&#36;',
				'AWG' => 'Afl.',
				'AZN' => 'AZN',
				'BAM' => 'KM',
				'BBD' => '&#36;',
				'BDT' => '&#2547;&nbsp;',
				'BGN' => '&#1083;&#1074;.',
				'BHD' => '.&#x62f;.&#x628;',
				'BIF' => 'Fr',
				'BMD' => '&#36;',
				'BND' => '&#36;',
				'BOB' => 'Bs.',
				'BRL' => '&#82;&#36;',
				'BSD' => '&#36;',
				'BTC' => '&#3647;',
				'BTN' => 'Nu.',
				'BWP' => 'P',
				'BYR' => 'Br',
				'BYN' => 'Br',
				'BZD' => '&#36;',
				'CAD' => '&#36;',
				'CDF' => 'Fr',
				'CHF' => '&#67;&#72;&#70;',
				'CLP' => '&#36;',
				'CNY' => '&yen;',
				'COP' => '&#36;',
				'CRC' => '&#x20a1;',
				'CUC' => '&#36;',
				'CUP' => '&#36;',
				'CVE' => '&#36;',
				'CZK' => '&#75;&#269;',
				'DJF' => 'Fr',
				'DKK' => 'DKK',
				'DOP' => 'RD&#36;',
				'DZD' => '&#x62f;.&#x62c;',
				'EGP' => 'EGP',
				'ERN' => 'Nfk',
				'ETB' => 'Br',
				'EUR' => '&euro;',
				'FJD' => '&#36;',
				'FKP' => '&pound;',
				'GBP' => '&pound;',
				'GEL' => '&#x20be;',
				'GGP' => '&pound;',
				'GHS' => '&#x20b5;',
				'GIP' => '&pound;',
				'GMD' => 'D',
				'GNF' => 'Fr',
				'GTQ' => 'Q',
				'GYD' => '&#36;',
				'HKD' => '&#36;',
				'HNL' => 'L',
				'HRK' => 'kn',
				'HTG' => 'G',
				'HUF' => '&#70;&#116;',
				'IDR' => 'Rp',
				'ILS' => '&#8362;',
				'IMP' => '&pound;',
				'INR' => '&#8377;',
				'IQD' => '&#x639;.&#x62f;',
				'IRR' => '&#xfdfc;',
				'IRT' => '&#x062A;&#x0648;&#x0645;&#x0627;&#x0646;',
				'ISK' => 'kr.',
				'JEP' => '&pound;',
				'JMD' => '&#36;',
				'JOD' => '&#x62f;.&#x627;',
				'JPY' => '&yen;',
				'KES' => 'KSh',
				'KGS' => '&#x441;&#x43e;&#x43c;',
				'KHR' => '&#x17db;',
				'KMF' => 'Fr',
				'KPW' => '&#x20a9;',
				'KRW' => '&#8361;',
				'KWD' => '&#x62f;.&#x643;',
				'KYD' => '&#36;',
				'KZT' => 'KZT',
				'LAK' => '&#8365;',
				'LBP' => '&#x644;.&#x644;',
				'LKR' => '&#xdbb;&#xdd4;',
				'LRD' => '&#36;',
				'LSL' => 'L',
				'LYD' => '&#x644;.&#x62f;',
				'MAD' => '&#x62f;.&#x645;.',
				'MDL' => 'MDL',
				'MGA' => 'Ar',
				'MKD' => '&#x434;&#x435;&#x43d;',
				'MMK' => 'Ks',
				'MNT' => '&#x20ae;',
				'MOP' => 'P',
				'MRU' => 'UM',
				'MUR' => '&#x20a8;',
				'MVR' => '.&#x783;',
				'MWK' => 'MK',
				'MXN' => '&#36;',
				'MYR' => '&#82;&#77;',
				'MZN' => 'MT',
				'NAD' => '&#36;',
				'NGN' => '&#8358;',
				'NIO' => 'C&#36;',
				'NOK' => '&#107;&#114;',
				'NPR' => '&#8360;',
				'NZD' => '&#36;',
				'OMR' => '&#x631;.&#x639;.',
				'PAB' => 'B/.',
				'PEN' => 'S/',
				'PGK' => 'K',
				'PHP' => '&#8369;',
				'PKR' => '&#8360;',
				'PLN' => '&#122;&#322;',
				'PRB' => '&#x440;.',
				'PYG' => '&#8370;',
				'QAR' => '&#x631;.&#x642;',
				'RMB' => '&yen;',
				'RON' => 'lei',
				'RSD' => '&#x434;&#x438;&#x43d;.',
				'RUB' => '&#8381;',
				'RWF' => 'Fr',
				'SAR' => '&#x631;.&#x633;',
				'SBD' => '&#36;',
				'SCR' => '&#x20a8;',
				'SDG' => '&#x62c;.&#x633;.',
				'SEK' => '&#107;&#114;',
				'SGD' => '&#36;',
				'SHP' => '&pound;',
				'SLL' => 'Le',
				'SOS' => 'Sh',
				'SRD' => '&#36;',
				'SSP' => '&pound;',
				'STN' => 'Db',
				'SYP' => '&#x644;.&#x633;',
				'SZL' => 'L',
				'THB' => '&#3647;',
				'TJS' => '&#x405;&#x41c;',
				'TMT' => 'm',
				'TND' => '&#x62f;.&#x62a;',
				'TOP' => 'T&#36;',
				'TRY' => '&#8378;',
				'TTD' => '&#36;',
				'TWD' => '&#78;&#84;&#36;',
				'TZS' => 'Sh',
				'UAH' => '&#8372;',
				'UGX' => 'UGX',
				'USD' => '&#36;',
				'UYU' => '&#36;',
				'UZS' => 'UZS',
				'VEF' => 'Bs F',
				'VES' => 'Bs.S',
				'VND' => '&#8363;',
				'VUV' => 'Vt',
				'WST' => 'T',
				'XAF' => 'CFA',
				'XCD' => '&#36;',
				'XOF' => 'CFA',
				'XPF' => 'Fr',
				'YER' => '&#xfdfc;',
				'ZAR' => '&#82;',
				'ZMW' => 'ZK',
			)
		);
		$currency_symbol = isset( $symbols[ $currency ] ) ? $symbols[ $currency ] : '';

		return apply_filters( 'hubloy-membership_currency_symbol', $currency_symbol, $currency );
	}

	/**
	 * Get Membership currency
	 *
	 * @since 1.0.0
	 *
	 * @return string
	 */
	public static function get_membership_currency() {
		$settings = new \HubloyMembership\Model\Settings();
		$general  = $settings->get_general_settings();
		$currency = $general['currency'];
		$code     = self::get_currency_symbol( $currency );
		return apply_filters( 'hubloy-membership_get_membership_currency', $code, $currency );
	}


	/**
	 * Formats a number to display a valid price.
	 *
	 * @param  numeric $price
	 *
	 * @since  1.0.0
	 *
	 * @return numeric
	 */
	public static function format_price( $price ) {
		$formatted = number_format_i18n( $price, 2 );

		return apply_filters(
			'hubloy-membership_format_price',
			$formatted,
			$price
		);
	}
}

